---
apiVersion: v1
kind: Service
metadata:
  name: keep-ecdsa-4
  namespace: default
  labels:
    app: keep
    type: ecdsa
    id: "4"
spec:
  ports:
    - port: 3919
      targetPort: 3919
      name: tcp-3919
  selector:
    app: keep
    type: ecdsa
    id: "4"
