---
apiVersion: v1
kind: Service
metadata:
  name: keep-ecdsa-3
  namespace: default
  labels:
    app: keep
    type: tecdsa
    id: '3'
spec:
  type: LoadBalancer
  ports:
    - port: 3919
      targetPort: 3919
      name: tcp-3919
  selector:
    app: keep
    type: tecdsa
    id: '3'
