:toc: macro

= RFC 2: tBTC liquidation recovery functionality

:icons: font
:numbered:
toc::[]

== Background

// tag::background[]
The Keep ECDSA client is a generic client for ECDSA keeps, which are on-chain
smart contract representations of a signing group that can provide on-demand
key generation and signature services for a consumer application (represented
by another smart contract). These applications occasionally require
application-specific functionality that is best handled by the ECDSA client.
tBTC is one such application that requires certain functionality specific to
it implemented in the ECDSA client. RFC 1 describes an approach for handling
certain, but not all, tBTC-specific functionality.

In the Ethereum deployment of the tBTC system, the ECDSA keeps secure their
correct operation by putting up collateral in the form of ETH on Ethereum. In
cases where the collateral becomes insufficient for the tBTC system to
guarantee its invariants (an amount that is controllable in the tBTC contracts),
the tBTC system is authorized to _seize_ this collateral, and begin an auction
process to bring itself back into balance.

In these scenarios, the ECDSA keep signers are in control of BTC that can be
split among their owners. This RFC seeks to outline a tBTC-specific
functionality that would allow the clients in the signer group to
automatically recover the BTC to designated addresses on the Bitcoin chain.
// end::background[]

=== Current Functionality

ECDSA clients currently monitor the chain for notifications that a Keep has
closed abnormally, in particular in the function
https://github.com/keep-network/keep-ecdsa/blob/b916eaa491b886fb6c7cde2706d225b5b85ac2a2/pkg/client/client.go#L778[`monitorKeepTerminatedEvent`].
For tBTC, a termination indicates that the keep backing a deposit has been
closed without a successful redemption, meaning that the keep still holds
BTC. Upon receiving a termination event, the client waits for a set number of
block confirmations to occur in order to be sure the event will not be
reorged away, then archives its key material, removes the keep from the local
list of active keeps, and finally stops monitoring for any other events
related to that keep.

Notably absent in the current ECDSA client's feature set is any interaction
with the Bitcoin chain. In particular, the ECDSA client does not contain any
functionality for connecting to a Bitcoin node, nor does it at any point
assemble Bitcoin data.

== Proposal

=== Goal

This proposal is focused on achieving a "least effort" implementation of a
recovery protocol that can handle happy paths for BTC distribution. Where
relevant, it points out _unhappy_ paths and may outline how they might be
dealt with in the future, but these unhappy paths are explicitly considered
out of scope for this RFC.

Additionally, this proposal avoids _strictly requiring_ a connection to a
Bitcoin node, as that is an additional piece of infrastructure that triggers
additional requirements for larger staking providers that may be operating
many nodes on behalf of multiple stakers.

=== Implementation Behaviors

It is important to observe that interaction with the Bitcoin chain is
_strictly unnecessary_ to construct and sign a Bitcoin transaction that
transmits the BTC held by a keep to n addresses, split evenly.

==== Bitcoin Transaction Requirements

The specific goal to recover BTC from a terminated keep is an N-way split of
the BTC, ~1/N going to each of the N signers in the signing group. To do this, a
Bitcoin transaction can be constructed with a single input (the UTXO that funded
the tBTC deposit) and N outputs (one for each signer). A fee, F, is subtracted
from the deposit's lot size, L, and (L-F)/N BTC is sent to each signer.

To compute the per-signer amount, the client needs to know:

- N, the number of signers in the group.
- F, the desired fee.
- L, the deposit lot size.

Separately from the amount, the Bitcoin sighash must be computed in order to
construct a transaction that can spend the tBTC deposit's UTXO; see the tBTC
spec's section on https://docs.keep.network/tbtc/#sighash[Standardized
Sighash Construction] for an introduction to this process. Computing the sighash
requires two additional pieces of data:

- The previous outpoint, which is the concatenation of the funding UTXO's
  32-byte little-endian transaction hash followed by the 4-byte little-endian
  index of the output pointing to the funding UTXO.
- The previous output script, which is to say the Bitcoin address
  corresponding to the deposit.

Notably, both of these pieces of data can be retrieved or computed solely
from data available on the tBTC deposit contract (the previous outpoint
cannot be retrieved solely from the ECDSA keep contract, but requires the
associated tBTC deposit contract).

Finally, once the per-signer amount and sighash are both known, constructing the
signed Bitcoin transaction requires a few more pieces of information:

- The signature of the sighash, which must be generated via the threshold ECDSA
  functionality of the keep.
- The public key of the current holder, which in this case is the keep and
  should be computable locally by each signer.
- For each of the signers, a Bitcoin address to receive the split amount.

==== Required Inputs

From this, we reach the full set of required inputs and where they can be
procured or computed:

- N, the number of signers in the group, available on the Keep contract
  from the `getMembers` view method, but also tracked locally on the client
  alongside the members of the keep.
- L, the deposit lot size, available on the tBTC deposit contract from the
  `lotSizeSatoshis` view method.
- The previous outpoint describing the deposit UTXO, available on the tBTC
  deposit contract from the `fundingInfo` view method, which returns it as
  the third `utxoOutpoint` entry in its 3-part return tuple.
- The keep's public key, available on the Keep contract from the
  `getPublicKey` view method.
- The deposit's Bitcoin redeem script, straightforwardly computable from the
  keep's public key by compressing the public key; this is briefly covered in
  the implementation <<output-script>> section.
- One Bitcoin address per signer, specified on the client in a way detailed
  in the section on <<recovery-address>>.
- The keep's signature on the sighash produced by the previous items,
  computed via the threshold ECDSA protocol in a way detailed in the section on
  the <<signing-protocol>>.
- F, the desired fee, which is a function of the going feerate on the Bitcoin
  network and the number of bytes in the final transaction.

The desired fee is the most problematic one to procure under the goal of not
strictly requiring a Bitcoin node connection, as generally a Bitcoin node
provides estimates of the feerates that will achieve transaction confirmation
within a certain amount of time. A short-term solution is proposed in the
section on <<bitcoin-fee>>.

[[recovery-address]]
===== Specifying an Operator's Bitcoin Recovery Address

To specify a given operator's Bitcoin Recovery Address, this proposal
suggests adding a single key to the `Extensions.TBTC.BTCRefunds` config
entry, `BeneficiaryAddress`. The value for this key should be one of:

- A simple BTC address.
- An xpub, ypub, or zpub that allows the client to derive new addresses for
  each refund.

The challenge with a *pub is that, to avoid reuse, it needs to do one of two
things:

- Be able to check, on-chain, whether a given address has been used; or,
- Have a *pub that is only meant for use by the client, and have the client
  track the latest address generated (as an index starting at 0).

To avoid _strictly requiring_ a connection to a Bitcoin node, this RFC
proposes tracking the latest address generated, and allowing an additional
config key, `TargetDerivationStartIndex`, that sets a starting point for such
derivations. The client should write the updated index to the `current/`
directory that tracks active key shares, to an encrypted file named
`current-btc-refund-derivation-index`. The operator should then seek to
obtain from the staker an extended public key that is only used for this
purpose. In cases where in-memory/on-disk derivation index and config file index
both exist, the highest index should be used.

If an optional Bitcoin node connection is available (see <<electrs>>), the
client should additionally check a derived address for a balance before
publishing. To do this, a GET request to `/address/<address>` should be issued,
and the JSON response inspected for a `tx_count` of 0. When such a connection is
available, if the client finds an address is already used, it should increment
the derivation index and check again. If the GET request fails, the index should
be assumed to be valid, as if the Bitcoin node connection were not available.

==== Modification of key material archiving

In the current client, key material is archived as soon as the ECDSA keep
contract a client is participating in moves into the CLOSED or TERMINATED
state. This RFC revises that behavior to only archive on transition to CLOSED.
When contracts transition into TERMINATED state and that transition is
confirmed (by waiting
https://github.com/keep-network/keep-ecdsa/blob/master/pkg/client/client.go#L28-L31[`blockConfirmation`
blocks]), the client should immediately begin <<bitcoin-fee,Bitcoin fee
resolution>> followed by the <<signing-protocol>> and finally
<<transaction-submission,transaction submission>>. Only when signing and
transaction submission (whether via logging or API) completes or times out
should the associated key material be archived.

On startup, if a client sees that an unarchived keep is in the TERMINATED
state and has been in that state for `blockConfirmation` blocks, it should
move directly to <<bitcoin-fee,Bitcoin fee resolution>>, unless an optional
Bitcoin node connection is available (see <<electrs>>). In this case, the
client should check the keep's associated deposit for an unspent balance by
issuing a GET request to `/tx/:txid/outspend/:vout`, using the deposit's
`fundingInfo().utxoOutpoint` to derive the transaction id and vout, and only
start the signing process if the JSON result has a `spent` value of false. If
`spent` is `true` and `status.confirmed` is `false`, a retry should occur
after an hour until `spent` is `true`, `status.confirmed` is `true`, and
`status.block_height` is at least 6 blocks past the value returned by issuing
a GET request to `/blocks/tip/height`. If this occurs, the key material
should be archived.

Note that the output spend may go from being `spent` and unconfirmed to being
unspent if the transaction spending the UTXO is dropped from the mempool
before being included in a block, at which point the bitcoin fee resolution
and signing process should proceed as if the keep was just terminated.

[[bitcoin-fee]]
===== Dealing with the Bitcoin Fee

The Bitcoin fee used for clients is something all three signers must agree
on, since it is part of the sighash. To agree on a fee, this proposal
suggests adding a single key to the `Extensions.TBTC.BTCRefunds` config
entry, `MaxFeePerVByte`, which is a value in sats per vByte that represents
the maximum fee per vByte this client is willing to pay in refund
transactions. The default for this value should be 75 sats per vByte.

If an optional Bitcoin connection is available (see <<electrs>>), the client
should look up the 25-block suggested fee per vByte and, if it is available
and nonzero, should replace the hardcoded max fee with this value. 25 blocks
means confirmation within ~4 hours. The default of 75 sats per vByte is aimed
to be slightly higher than a reasonable value for 25 blocks, though of course
fee market fluctuation can change this at a moment's notice. The 25-block
suggested fee per vByte should be available at the `/fee-estimates` endpoint
of the REST API, which returns a JSON object with the key `"25"`
corresponding to this fee.

There is one exception to the rule that the 25-block suggested fee should be
used in the presence of a Bitcoin connection. If this suggested fee would result
in a fee consuming more than 5% of the UTXO value that is being split, then
the lesser of the 25-block suggested fee and `MaxFeePerVByte` configured fee
should be used. Because the true fee computation requires that the full
transaction be assembled, the transaction fee should be estimated by assuming
the final transaction will be 175 vBytes, which should be very close to
accurate given the regular structure of liquidation refund transactions.

If the final fee is computed as being >5% of UTXO value, the client should log
a WARN message so that the operator can be aware of this and revise their max
fee per vByte if desired.

Once each client has its max fee, it will proceed with the
<<signing-protocol>>. This protocol involves exchanging the max fees of all
clients and choosing the lowest max fee acceptable to all clients, and using
that as the fee for the final transaction.

[[signing-protocol]]
===== Signing Protocol

The signing protocol proceeds very much like the standard ECDSA signing
protocol, but starts in a different place. In the standard ECDSA signing
protocol, an on-chain `SignatureRequested` event triggers the client to
https://github.com/keep-network/keep-ecdsa/blob/87716e91f225a3c01501ae73a75db83f79230497/pkg/ecdsa/tss/tss.go#L132[join
a broadcast channel] and perform a
https://github.com/keep-network/keep-ecdsa/blob/87716e91f225a3c01501ae73a75db83f79230497/pkg/ecdsa/tss/protocol_ready.go#L24[ready
protocol] to ensure all signers are ready to sign.

During standard signing, the ready protocol communicates a Ready message that
solely carries the sender ID. Once all three clients have received each other's
ready messages, the ready protocol completes and the signing protocol starts.
For liquidation recovery purposes, this ready protocol is the one that is
adjusted. Instead of only announcing sender IDs, the three signers announce a
ready message with three components:

- The sender ID.
- The BTC address to which the sender's share will be sent.
- The max fee per vByte the sender is willing to pay.

Once each client receives the ready messages from the two other nodes, it can
immediately choose the correct fee per vByte from the provided values (see
<<bitcoin-fee>>), construct the transaction object (see
<<transaction-construction>>), derive the sighash (see
<<sighash-derivation>>) and proceed into the signing process to sign that
sighash. Once a signature is computed, each client should construct the final
transaction (see <<final-transaction-construction>>) and submit it (see
<<transaction-submission>>).

When receiving the ready message from other nodes, a node should validate that
the announced BTC address can be parsed correctly by the tooling used to handle
transaction and sighash construction. If the announced BTC address cannot be
parsed, an error should be logged and the message should be treated as if it was
not received.

The retry mechanism for the signing process for liquidation recovery should be
identical to regular signing, repeating every 2 minutes that a signature has
not been completed successfully until the liquidation recovery timeout. Unlike
standard signing, the liquidation recovery timeout should be very long to allow
for node malfunctions to recover cleanly: this RFC recommends a default timeout
of 7 days.

[[transaction-submission]]
==== Submitting the Signed Transaction

Submitting a signed Bitcoin transaction requires a connection to a Bitcoin
node, direct or indirect. To avoid _strictly requiring_ a connection to a
Bitcoin node, this RFC proposes logging the signed transaction 5 times on the
WARN level with a descriptive prefix. Current operator guidance suggests that
more than 5 WARN level logs within 5 minutes should trigger a notification
for closer monitoring by operators, ensuring these logs will be noticed, at
which time the operator can choose to either broadcast the transaction or
relay it to someone else for broadcasting. The descriptive prefix will
further allow for targeted notifications by operators so that they can flag
these logs for follow-up action.

The suggested structure of the log message is:

```
2020-02-01T12:12:12.12-0800    WARN   keep-ecdsa   Please broadcast Bitcoin transaction 0010010101000828181124af234gbawed000
```

The first three components are the standard components emitted by the ECDSA
client's logging library, while the message itself begins with `Please broadcast
Bitcoin transaction`, followed by the hexadecimal string representing the signed
transaction. The signed transaction can be broadcast via manual submission to a
known node, via API access to a service provider like BlockCypher or
Blockstream, or via a manual form submission on a page like
https://live.blockcypher.com/btc/pushtx/ .

If an optional Bitcoin node connection is available (see <<electrs>>), the
client should attempt to publish the transaction by performing an HTTP POST
request to path `/tx`. The POST request body should be the signed transaction
hex, as would be logged in the WARN logs above. If the POST fails, the client
should log an error and then fall back on the standard way of surfacing the
transaction data without a node connection, as described above.

=== Implementation Details

There are a few implementation details that are worth calling out; in
particular, the *pub address derivation, the deposit output script
construction, the Bitcoin sighash construction, the Bitcoin transaction
construction, and the attachment of the signature to the Bitcoin transaction.
This proposal suggests this be done using the `btcsuite` series of Go
libraries, and each one is detailed below with draft code using those
libraries.

[[output-script]]
==== Deposit Output Script Construction

tBTC deposits always use Witness PubKeyHash in their funding UTXO. This means
that, to spend the funding UTXO, the deposit signing group must sign a sighash
that allows spending that UTXO. The signing process does this by including a
`scriptCode` as part of the the sighash (see <<sighash-construction>>). The
`scriptCode`, for Witness PubKeyHash transactions, is defined in BIP143.

This function constructs the relevant `scriptCode` bytes from the deposit's
public key:

```go
// import "github.com/btcsuite/btcd/btcec"
// import "github.com/btcsuite/btcutil"

// PublicKeyToP2WPKHOutputScript converts a public key to a Bitcion p2wpkh
// witness scriptCode that can spend an output sent to that public key's
// corresponding address.
//
// [BIP143]: https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki
func PublicKeyToP2WPKHScriptCode(
  publicKey *ecdsa.PublicKey,
  chainParams *chaincfg.Params,
) ([]byte, error) {
  // ecdsa.PublicKey and btcec.PublicKey are both method attachments to
  // Go's crypto/ecdsa.PublicKey, so we can cast.
  publicKeyBytes := (*btcec.PublicKey)(publicKey).SerializeCompressed()
  // Note that the scriptCode for a p2wpkh address is the equivalent of the
  // p2pkh scriptPubKey.
  pubKeyAddress, err := btcutil.NewAddressPubKey(publicKeyBytes, chainParams)
  if (err != nil) {
    return fmt.Errorf(
      "error deriving p2wpkh scriptCode from public key: [%s]",
      err,
    )
  }
  pkhAddress := pubKeyAddress.AddressPubKeyHash()

  script, err := txscript.PayToAddrScript(pkhAddress)
  if (err != nil) {
    return fmt.Errorf(
      "error deriving p2wpkh scriptCode from public key: [%s]",
      err,
    )
  }
  if (len(script) > 255) {
    return fmt.Errorf(
      "error deriving p2wpkh scriptCode from public key: [scriptCode too long]",
      len(script)
    )
  }

  // End goal here is a scriptCode that looks like
  // 0x1976a914{20-byte-pubkey-hash}88ac . 0x19 should be the length of the
  // script.
  return append([]byte{byte(len(script))}, script...)
}
```

==== Derivation of Bitcoin Addresses from Extended Public Keys

For best-practice Bitcoin support, this RFC requires that recovery addresses,
as specified in <<recovery-address>>, can be specified as extended public
keys. Extended public keys are generally prefixed by the string `xpub`, as
defined in BIP32. Two additional prefixes are possible: `ypub` is defined in
BIP49 and `zpub` is defined in BIP84.

The `github.com/btcsuite/btcutil/hdkeychain` package handles the key
derivation requirements; however, it always returns BIP44 addresses. As
such, some special handling is needed to detect `ypub` and `zpub` prefixes
and generate the appropriate address types (p2sh and p2wpkh, respectively).
While using the *pub prefix to indicate the address type is not ideal, and
other approaches are used in a few places, they are outside the scope of this
RFC.

Each *pub should come already set to the root path that addresses should
originate at (e.g. `m/0'/0'` for the first account in BIP32 bitcoin-core
wallets, `m/44'/0'/0'` for the first account in BIP44 wallets, and so on).
Addresses are derived as external chain addresses, i.e. at subpath `/0`.

Here is a sample function that could be used to implement this functionality
using the `hdkeychain` package and its relatives:

```go
// import "github.com/btcsuite/btcd/btcec"
// import "github.com/btcsuite/btcd/txscript"
// import "github.com/btcsuite/btcutil"

// DeriveAddress uses the specified extended public key and address index to
// derive an address string in the appropriate format at the specified address
// index. The extended public key is expected to already be at the account path
// level (e.g. m/44'/0'/0' for [BIP44] xpubs), and addresses are derived within
// the external chain subpath (`/0`). Thus, calling DeriveAddress with an xpub
// generated at m/44'/0'/0' and passing the address index 5 will produce the
// address at path m/44'/0'/0'/0/5.
//
// In cases where the extended public key is at depth 4, meaning the external or
// internal chain is already included, DeriveAddress will directly derive the
// address index at the existing depth.
//
// The returned address will be a p2pkh/p2sh address for prefixes xpub and tpub,
// (i.e. prefixed by 1, m, or n), a p2wpkh-in-p2sh address for prefixes ypub or
// upub (i.e., prefixed by 3 or 2), and a bech32 p2wpkh address for prefixes
// zpub or vpub (i.e., prefixed by bc1 or tb1).
//
// See [BIP32], [BIP44], [BIP49], and [BIP84] for more on address derivation,
// particular paths, etc.
//
// [BIP32]: https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki
// [BIP44]: https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki
// [BIP49]: https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki
// [BIP84]: https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki
func DeriveAddress(extendedPublicKey string, addressIndex int) (string, error)
{
  extendedKey, err := hdkeychain.NewKeyFromString(extendedPublicKey)
  if (err != nil) {
    return fmt.Errorf(
      "error parsing extended public key: [%s]",
      err,
    )
  }
  // For later usage---this is xpub/ypub/zpub/...
  publicKeyDescriptor = extendedPublicKey[0:4]

  externalChain := extendedKey
  if (externalChain.Depth() < 4) {
    // Descend to the external chain path, /0.
    externalChain, err = extendedKey.Child(0)
    if (err != nil) {
      return fmt.Errorf(
        "error deriving external chain path /0 from extended key: [%s]",
        err,
      )
    }
  }

  requestedPublicKey, err := externalChain.Child(addressIndex)
  if (err != nil) {
    return fmt.Errorf(
      "error deriving requested address index /0/%s from extended key: [%s]",
      addressIndex,
      err,
    )
  }

  // Now to decide how we want to serialize the address...
  var chainParams *chaincfg.Params
  switch publicKeyDescriptor {
  case "xpub", "ypub", "zpub":
    chainParams = &chaincfg.MainNetParams
  case "tpub", "upub", "vpub":
    chainParams = &chaincfg.TestNet3Params
  }

  requestedAddress, err := requestedPublicKey.Address(chainParams)

  var finalAddress btcutil.Address = requestedAddress
  switch publicKeyDescriptor {
  case "xpub", "tpub":
    // Noop, the address is already correct
  case "ypub", "upub":
    // p2wpkh-in-p2sh, constructed as per https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki#p2wpkh-nested-in-bip16-p2sh .
    scriptSig = append([]byte{0x00, 0x14}, requestedAddress.Hash160()[:]...)
    finalAddress = btcutil.NewAddressWitnessScriptHash(
      btcutil.Hash160(scriptSig),
      chainParams,
    )
  case "zpub", "vpub":
    // p2wpkh
    finalAddress, err = btcutil.NewAddressWitnessPubKeyHash(
      requestedAddress.Hash160()[:],
      chainParams,
    )
  }
  if (err != nil) {
    return fmt.Errorf(
      "failed to derive final address format from extended key: [%s]",
      err,
    )
  }

  return finalAddress.EncodeAddress()
}
```

[[transaction-construction]]
==== Construction of Unsigned Transaction

The unsigned transaction can be constructed from information about the
previous transaction, a fee per vbyte, a set of recipient addresses, and a
dummy signature and public key for the funding UTXO. This process results in
an almost-complete transaction with the associated final fee. The sample
function below shows the various inputs as well as how they can be combined
to produce the transaction

```go
// import "github.com/btcsuite/btcd/wire"
// import "github.com/btcsuite/btcd/txscript"

func ConstructUnsignedTransaction(
  previousOutputTransactionHashHex string, // <1>
  previousOutputIndex uint32,
  previousOutputValue int64, // <2>
  feePerVbyte int64, // <3>
  recipientAddresses []string,
  chainParams *chaincfg.Params, // <4>
) (*wire.MsgTx, error) {
    // If the previous output transaction hash is passed as a []byte, can use
    // chainhash.NewHash.
  previousOutputTransactionHash, err := chainhash.NewHashFromStr(
    previousOutputTransactionHashHex,
  )
  if err != nil {
    return "", fmt.Errorf(
      "error extracting outpoint transaction hash: [%s]",
      previousOutputTransactionHash,
    )
  }

  // The witness signature field is the DER signature followed by the hash type.
  // We write a dummy signature with 73 0 bytes. DER signatures vary in encoding
  // between 71, 72, and 73 bytes, so we choose the longest for fee purposes.
  dummySignatureForWitness := []byte{
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0,
    0, // one more dummy byte for the SigHashType
  }
  // The compressed public key requires 33 bytes.
  dummyCompressedPublicKeyForWitness := []byte{
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    0, 0, 0,
  }

  tx := wire.NewMsgTx(wire.TxVersion)
  txIn := wire.NewTxIn(
    wire.NewOutPoint(previousOutputTransactionHash, previousOutputIndex),
    nil, // scriptSig is empty here
    [][]byte{
      dummySignatureForWitness,
      dummyCompressedPublicKeyForWitness,
    },
  )
  txIn.Sequence = 0
  tx.AddTxIn(txIn)

  for _, recipientAddress := range recipientAddresses {
    address, err := btcutil.DecodeAddress(recipientAddress, chainParams)
    if err != nil {
      return "", fmt.Errorf(
        "error decoding output address [%s]: [%s]",
        recipientAddress,
        err,
      )
    }
    outputScript, err := txscript.PayToAddrScript(address)
    if err != nil {
      return "", fmt.Errorf(
        "error constructing script from output address [%s]: [%s]",
        recipientAddress,
        err,
      )
    }

    tx.AddTxOut(wire.NewTxOut(
      int64(0), // value is filled in after fee is computed below
      outputScript,
    ))
  }

  // Compute weight and vsize per [BIP141], except vsize is truncated
  // instead of rounded up, then compute the final fee and set the
  // per-recipient value. Could result in a fractionally low fee.
  weight := tx.SerializeSizeStripped()*3 + tx.SerializeSize()
  vsize := weight / 4
  fee := feePerVbyte * int64(vsize)
  perRecipientValue := (previousOutputValue - fee) / int64(len(recipientAddresses))
  for _, txOut := range tx.TxOut {
    txOut.Value = perRecipientValue
  }

  return tx, nil
}
```
<1> These two come from `fundingInfo().utxoOutpoint`, which has the transaction
    id as the first 32 little-endian bytes and the previous output index as
    its last 4 little-endian bytes.
<2> Comes from `fundingInfo().utxoValue`, a little-endian unsigned int.
<3> Derived as part of the <<signing-protocol>>.
<4> e.g. &chaincfg.MainNetParams or TestNet3Params


[[sighash-construction]]
==== Construction of Sighash for Signing

The sighash is constructed as the double-SHA256 of the preimage. The preimage
is defined in BIP143. Fortunately, once the dummy unsigned transaction is
available, btcutil provides the tooling to build the sighash. The sample
function call below shows how to construct the sighash once an unsigned
transaction is available from above the function in
<<transaction-construction>>. This sighash is the data then signed by the
signer group to produce a valid transaction (see the section on
<<final-transaction-construction>> for the rest of the process once the
signature has been computed):

```go
// import "github.com/btcsuite/btcd/txscript"

// unsignedTransaction := ConstructUnsignedTransaction(...)
sighashBytes, err := txscript.CalcWitnessSigHash(
  previousOutputScriptCode, // from PublicKeyToP2WPKHScriptCode
  txscript.NewTxSigHashes(unsignedTransaction),
  txscript.SigHashAll,
  unsignedTransaction,
  0, // sighash for the first input; there is only one input anyway
  previousOutputValue,
)
```

[[final-transaction-construction]]
==== Construction of Final Transaction

The final transaction can be constructed from the unsigned transaction
produced in <<transaction-construction>>, the signature of that transaction's
sighash from <<sighash-construction>>, and the public key of the signing group.
The sample function below shows the various inputs as well as how they can
be combined to produce the final transaction hex string that can then be
submitted to the chain:

```go
func BuildSignedTransactionHexString(
  unsignedTransaction *wire.MsgTx, // <1>
  signature *ecdsa.Signature, // <2>
  publicKey *ecdsa.PublicKey, // <3>
) (string, error) {
  // For safety's sake, work on a deep copy, as mutations follow.
  signedTransaction := unsignedTransaction.Copy()

  btcSignature := &btcec.Signature{R: signature.R, S: signature.S}

  // The witness is for the first input, since this is known to be a
  // single-input transaction.
  signedTransaction.TxIn[0].Witness = wire.TxWitness{
    // The witness signature field is the DER signature followed by the hash type.
    append(btcSignature.Serialize(), byte(txscript.SigHashAll)),
    // The second part of the witness is the compressed public key.
    (*btcec.PublicKey)(publicKey).SerializeCompressed(),
  }

  // BtcEncode writes bytes, we wrap it in an hex encoder wrapped
  // around a strings.Builder to get a hex string.
  transactionHexBuilder := &strings.Builder{}
  transactionWriter := hex.NewEncoder(txBuilder)
  signedTransaction.BtcEncode(
    transactionWriter,
    wire.ProtocolVersion,
    wire.WitnessEncoding,
  )

  return transactionHexBuilder.String(), nil
}
```
<1> Constructed using the function in <<transaction-construction>>.
<2> Computed via the <<signing-protocol>>.
<3> Available on the signer directly (see
    https://github.com/keep-network/keep-ecdsa/blob/f240e81002a7b26eb6326be068dbf80b53bc0a18/pkg/ecdsa/tss/signer.go#L33[`ThresholdSigner.PublicKey()`]).

=== Limitations

The biggest limitation is trusting the operator to manage the return BTC
address. This limitation is described in more detail in the appendix on
<<recovery-address-ownership>>.

Additionally, this approach is not mediated by a smart contract in any way;
as such, it relies entirely on the cooperation of the operators. Since there
is a value-positive outcome for each operator for cooperating, this should be
sufficient in the 3-of-3 signing groups that operate tBTC v1.

[appendix]
[[electrs]]
== Optional Electrs REST API Server

The proposal <<Goal>> section proposes avoiding a strict requirement for a
Bitcoin node; however, several parts of the proposal feature an optional
dependency on an Electrs REST API server. This server should be expected to
adhere to the
https://github.com/Blockstream/esplora/blob/master/API.md[Blockstream electrs
REST API], currently implemented by the
https://github.com/Blockstream/electrs/[Blockstream fork of electrs]. This fork
is open source and has a Docker image available; it must be connected to a
bitcoind instance.

To configure this, the `Extensions.TBTC.ElectrsURL` key can be set to the
appropriate URL. This configuration option should default to
`https://blockstream.info/api/`, but the operator should be allowed to be set
it to a blank string to disable integration altogether.

[appendix]
[[recovery-address-ownership]]
== Recovery Address Ownership

The Keep staking model designates four roles in a token delegation relationship,
which is used to stake the KEEP token to make it eligible for work in the
network:

staker:: The token holder staking the KEEP token.
authorizer:: The role responsible for authorizing new contracts that may
  interact with the staked KEEP, making the staked KEEP eligible for use in
  new applications built on the network.
operator:: The role responsible for actually performing the duties required by
  authorized contracts in order to fulfill the obligations of the staked KEEP
  on the network.
beneficiary:: The role that receives rewards and fee payments for work done by
  the operator in a given delegation relationship.

The Keep network does not explicitly provide for operators to be paid for their
work; indeed, the staker, authorizer, operator, and beneficiary may all be the
same Ethereum account, may all be separate accounts, or may be distributed among
2 or 3 accounts. The staker ultimately decides how to distribute the roles at
the time that tokens are delegated.

Notably, all of these roles are specified as Ethereum addresses, which leaves
open the question of who designates the Bitcoin address that will receive
recovered BTC. Generally the system design favors the beneficiary address as
the sink to which all outgoing funds are routed in a delegation relationship,
and gives the staker the final say in what beneficiary address to use.

This RFC is a slight departure from this mechanism, in that it is ultimately
the operator who designates the beneficiary for liquidation recovery purposes
(this beneficiary is on the Bitcoin chain rather than the Ethereum chain, of
course). At any time, if the staker notes misbehavior by the operator, including
designating an inappropriate beneficiary address, they can undelegate their
stake, thus preventing the operator from being able to do further work on their
behalf.

One way to adapt this approach would be to allow the beneficiary address to sign
the desired Bitcoin beneficiary information, and have the ECDSA client verify
this signature before using it. Unfortunately, a malicious operator can simply
create a build of the client that omits this check. Though a complex cross-chain
protocol could be devised for committing to an address, we instead make the
assumption that the operator and staker have coordinated solid enough terms to
ensure that the operator will not send liquidation recovery BTC to a bad
address.

As a special case, for a DAO staker that may not have straightforward legal
recourse, an agreement to send BTC to a particular address can be enforced
on-chain via an operator bond or other mechanism attached to the same SPV
proof mechanism that powers tBTC itself, to prove that an operator authorized
dispensation of BTC to a different address and punish them, or withhold future
payments.

[bibliography]
== Related Links

- https://docs.keep.network/tbtc/[tBTC specification]
- https://github.com/Blockstream/esplora/blob/master/API.md[Blockstream API docs]
- https://github.com/bitcoin/bips/blob/master/bip-0032.mediawiki[BIP32:
  Hierarchical Deterministic Wallets]
- https://github.com/bitcoin/bips/blob/master/bip-0044.mediawiki[BIP44:
  Multi-Account Hierarchy for Deterministic Wallets]
- https://github.com/bitcoin/bips/blob/master/bip-0049.mediawiki[BIP49:
  Derivation scheme for P2WPKH-nested-in-P2SH based accounts]
- https://github.com/bitcoin/bips/blob/master/bip-0084.mediawiki[BIP84:
  Derivation scheme for P2WPKH based accounts]
- https://github.com/bitcoin/bips/blob/master/bip-0141.mediawiki[BIP141:
  Segregated Witness (Consensus layer)]
- https://github.com/bitcoin/bips/blob/master/bip-0143.mediawiki[BIP143:
  Transaction Signature Verification for Version 0 Witness Program]
