name: Gosec

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  scan:
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - uses: actions/checkout@v2
      - uses: securego/gosec@master
        with:
          args: |
            -exclude-dir=pkg/chain/gen
            ./...